sudo: required
services:
  - docker

before_install:
  - docker build -t mvignjevic/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mvignjevic/react-test npm test -- --coverage

after_success:
  - docker build -t mvignjevic/multi-client ./client
  - docker build -t mvignjevic/multi-nginx ./nginx
  - docker build -t mvignjevic/multi-server ./server
  - docker build -t mvignjevic/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  # Now take those images and push them to docker hub
  - docker push mvignjevic/multi-client
  - docker push mvignjevic/multi-nginx
  - docker push mvignjevic/multi-server
  - docker push mvignjevic/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-225614405924
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY